# Generated by Django 2.2.4 on 2019-08-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=50)),
                ('country_maestro', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publication_date', models.DateTimeField()),
                ('gendre', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('cover', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('maestros', models.ManyToManyField(to='literature.Maestro')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_number', models.IntegerField()),
                ('text_page_number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.Part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.Work'),
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('essay_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.Text')),
            ],
        ),
    ]
