# Generated by Django 2.2.4 on 2019-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestro',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Love', 'Love'), ('Reality', 'Reality'), ('Adventure', 'Adventure')], default='exit', max_length=8),
            preserve_default=False,
        ),
    ]
