# Generated by Django 2.2.4 on 2019-08-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0002_auto_20190828_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
