# Generated by Django 2.2.4 on 2019-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0002_userlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='works_owned',
            field=models.ManyToManyField(blank=True, to='literature.Work'),
        ),
    ]
