# Generated by Django 2.2.4 on 2019-08-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0003_auto_20190816_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'verbose_name': 'User Library', 'verbose_name_plural': 'User Library'},
        ),
    ]
