# Generated by Django 2.2.4 on 2019-08-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0004_auto_20190817_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='category',
            field=models.CharField(choices=[('HR', 'Horror'), ('LV', 'Love'), ('RL', 'Reality'), ('AV', 'Adventure')], default='', max_length=4),
            preserve_default=False,
        ),
    ]
