# Generated by Django 2.2.4 on 2019-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0005_maestro_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='category',
            field=models.CharField(choices=[('HORROR', 'Horror'), ('LOVEV', 'Love'), ('REALITY', 'Reality'), ('ADVENTURE', 'Adventure')], max_length=4),
        ),
    ]
