# Generated by Django 2.2.4 on 2019-08-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0007_auto_20190821_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='category',
            field=models.CharField(choices=[('HORROR', 'Horror'), ('LOVE', 'Love'), ('REALITY', 'Reality'), ('ADVENTURE', 'Adventure')], max_length=8),
        ),
    ]
