# Generated by Django 2.2.4 on 2019-08-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0009_auto_20190822_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='slug_description',
            new_name='slug',
        ),
    ]
