# Generated by Django 2.2.4 on 2019-08-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0010_auto_20190822_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='gendre',
            new_name='description',
        ),
    ]
