# Generated by Django 2.2.4 on 2019-08-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0012_auto_20190822_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Love', 'Love'), ('Reality', 'Reality'), ('Adventure', 'Adventure')], max_length=8),
        ),
    ]
