# Generated by Django 2.2.4 on 2019-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0013_auto_20190824_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(to='literature.Category'),
        ),
    ]
