# Generated by Django 2.2.4 on 2019-08-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0014_auto_20190824_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestro',
            old_name='complete_name',
            new_name='completename',
        ),
    ]
