# Generated by Django 2.2.4 on 2019-08-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0015_auto_20190825_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='categories',
        ),
    ]
