# Generated by Django 2.2.4 on 2019-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0016_remove_work_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(to='literature.Category'),
        ),
    ]
