# Generated by Django 2.2.4 on 2019-08-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0017_work_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='longbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='worldwide_appreciated',
            field=models.BooleanField(default=False),
        ),
    ]
