# Generated by Django 2.2.4 on 2019-08-27 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0019_remove_work_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='literature.Category'),
            preserve_default=False,
        ),
    ]
