# Generated by Django 2.2.4 on 2019-08-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0022_auto_20190827_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='bestseller',
        ),
        migrations.RemoveField(
            model_name='work',
            name='longbook',
        ),
        migrations.RemoveField(
            model_name='work',
            name='worldwide_appreciated',
        ),
    ]
