# Generated by Django 2.2.4 on 2019-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0023_auto_20190827_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='categories',
        ),
        migrations.AddField(
            model_name='work',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='longbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='worldwide_appreciated',
            field=models.BooleanField(default=False),
        ),
    ]
