# Generated by Django 2.2.4 on 2019-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0024_auto_20190827_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(to='literature.Category'),
        ),
    ]
