# Generated by Django 2.2.4 on 2019-08-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0025_work_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
