# Generated by Django 2.2.4 on 2019-08-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0027_auto_20190827_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='publication_date',
        ),
    ]
