# Generated by Django 2.2.4 on 2019-08-27 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0028_remove_work_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='longbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='worldwide_appreciated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(to='literature.Category'),
        ),
    ]
