# Generated by Django 2.2.4 on 2019-08-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0029_auto_20190827_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='work',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='literature.Category'),
            preserve_default=False,
        ),
    ]
